### ISSUE TITLE
Error parsing url

### ISSUE THREAD

**Issue by seik** [seik/archivator#1]
Starting url:  `https://daringfireball.net`

Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/seik/Dev/Personal/archivator/archivator/main.py", line 68, in <module>
    self.archive_urls()
  File "/home/seik/Dev/Personal/archivator/archivator/main.py", line 58, in run
    def run(self):
  File "/home/seik/Dev/Personal/archivator/archivator/main.py", line 30, in collect_page_urls
    return f"{self.base_url}{url}" if url.startswith("/") else url 
  File "/home/seik/.cache/pypoetry/virtualenvs/archivator-GvrDIugD-py3.8/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/seik/.cache/pypoetry/virtualenvs/archivator-GvrDIugD-py3.8/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/seik/.cache/pypoetry/virtualenvs/archivator-GvrDIugD-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/seik/.cache/pypoetry/virtualenvs/archivator-GvrDIugD-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 637, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/seik/.cache/pypoetry/virtualenvs/archivator-GvrDIugD-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 728, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '\\"https://daringfireball.net/2020/03/the_2020_macbook_air\\"'
```

**Comment by seik** [comment]
Closed for now. 

Fixed by not scrapping non html responses. In this case the URL pointed an RSS feed, which has encoded characters in the href elements.
